name: Pulumi Remove Stack
on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack to remove'
        required: true

jobs:
  preview:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      id-token: write
      contents: read
    name: Pulumi Remove Stack ${{ matrix.arrays.stack.name }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: 📦️ Pulumi Install 📦️
        uses: pulumi/actions@v5

      - name: Pulumi Remove Stack 🔨
        working-directory: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi stack rm ${{ inputs.stack }}
